version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: backend-app
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    networks:
      - oceans_stack

  frontend:
    build:
      context: ./frontend
    container_name: frontend-app
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    networks:
      - oceans_stack
    environment:
      - VITE_API_URL=http://backend-app:3000/api
  
networks:
  oceans_stack:
    driver: bridge

