# Etapa de build (compila TypeScript)
FROM node:24-alpine3.21 as builder

WORKDIR /backend

COPY package*.json ./
RUN npm install

COPY tsconfig*.json ./

COPY src ./src
RUN npm run build


# #Etapa de producción (solo JS compilado)
FROM node:24-alpine3.21

WORKDIR /production

COPY package*.json ./
RUN npm install --production

COPY --from=builder /backend/dist ./dist

CMD ["node", "dist/app.js"]
